cookbook 'apt'
cookbook 'ark'
cookbook 'bluepill'
cookbook 'build-essential'
cookbook 'java'
# cookbook 'nginx'
cookbook 'rsyslog'
cookbook 'windows'
cookbook 'yum'
cookbook 'yum-epel'
cookbook 'ant'
cookbook 'dmg'
cookbook 'chef_handler'
# cookbook 'runit'

cookbook 'ohai', git: 'https://github.com/opscode-cookbooks/ohai.git', tag: '1.1.2'
# cookbook 'elasticsearch', git: 'https://github.com/elasticsearch/cookbook-elasticsearch'
cookbook 'elasticsearch', git: 'https://github.com/stuart-warren/cookbook-elasticsearch', branch: 'customize_attributes'
cookbook 'monit', git: 'https://github.com/apsoto/monit'
cookbook 'python', git: 'https://github.com/poise/python'
# cookbook 'logstash', git: 'https://github.com/lusis/chef-logstash.git', tag: '0.7.7'
# cookbook 'logstash', git: 'https://github.com/lusis/chef-logstash.git', branch: 'logstash_1.4'
cookbook 'logstash', git: 'https://github.com/stuart-warren/chef-logstash.git', branch: 'customize_attributes'
cookbook 'git', git: 'https://github.com/jssjr/git.git'
cookbook 'kibana', git: 'https://github.com/lusis/chef-kibana.git'
cookbook 'logrotate', git: 'https://github.com/stevendanna/logrotate.git'
cookbook 'pleaserun', git: 'https://github.com/paulczar/chef-pleaserun.git'

