
# set['elasticsearch']['version'] = '1.1.0'
# set['elasticsearch']['cluster']['name'] = 'elasticsearch'
# set['elasticsearch']['node']['master'] = true
# set['elasticsearch']['node']['data'] = true
# set['elasticsearch']['logging']['action.discovery.ec2'] = 'WARN'
# # set['elasticsearch']['plugins']['elasticsearch/elasticsearch-cloud-aws']['version'] = '2.1.0'
# set['elasticsearch']['cloud']['aws']['region'] = 'eu-west-1'
# set['elasticsearch']['index']['number_of_shards'] = 3
# set['elasticsearch']['index']['number_of_replicas'] = 2
# set['elasticsearch']['discovery']['type'] = 'ec2'
# set['elasticsearch']['discovery']['zen']['minimum_master_nodes'] = 1
# set['elasticsearch']['discovery']['ping']['multicast']['enabled'] = false
# set['elasticsearch']['discovery']['ec2']['tag']['opsworks:stack'] = "elasticsearch"
# set['elasticsearch']['limits']['nofile'] = 655350
# set['elasticsearch']['custom_config']['cluster.routing.allocation.awareness.attributes'] = 'aws_availability_zone'
# set['elasticsearch']['custom_config']['index.refresh_interval'] = '3s'
# set['elasticsearch']['custom_config']['indices.fielddata.cache.size'] = '15%'
# set['elasticsearch']['custom_config']['indices.fielddata.cache.expire'] = '1h'
# set['elasticsearch']['custom_config']['indices.cache.filter.size'] = '15%'
